# Proxy runtime for the imported Amazon Bedrock Agent "{{agentName}}".
# Generated by `agentcore project create/add runtime --type import`. Requests to
# this runtime are forwarded to the Bedrock Agent, and its reply is streamed
# back — edit or replace this file to take ownership of the behavior.

import asyncio
import hashlib
import os
import re
import uuid

import boto3
from bedrock_agentcore.runtime import BedrockAgentCoreApp

AGENT_ID = os.environ.get("BEDROCK_AGENT_ID", "{{agentId}}")
AGENT_ALIAS_ID = os.environ.get("BEDROCK_AGENT_ALIAS_ID", "{{agentAliasId}}")
AGENT_REGION = os.environ.get("BEDROCK_AGENT_REGION", "{{agentRegion}}")
BEDROCK_SESSION_ID_PATTERN = re.compile(r"^[0-9A-Za-z._:-]{2,100}$")
END_OF_COMPLETION = object()

app = BedrockAgentCoreApp()
client = boto3.client("bedrock-agent-runtime", region_name=AGENT_REGION)


def normalize_session_id(value):
    """Return a stable Bedrock-compatible session id."""
    if isinstance(value, str) and BEDROCK_SESSION_ID_PATTERN.fullmatch(value):
        return value
    if isinstance(value, str) and value:
        return hashlib.sha256(value.encode("utf-8")).hexdigest()
    return uuid.uuid4().hex


def next_completion_event(completion):
    """Read one streaming event without leaking StopIteration into asyncio."""
    try:
        return next(completion)
    except StopIteration:
        return END_OF_COMPLETION


@app.entrypoint
async def invoke(payload, context):
    """Forward the prompt to the Bedrock Agent and stream its completion."""
    if not isinstance(payload, dict):
        yield "Invalid payload; expected a JSON object with a non-empty 'prompt' field."
        return

    prompt = payload.get("prompt", "")
    if not isinstance(prompt, str) or not prompt:
        yield "No query provided; include a 'prompt' field in the payload."
        return

    # Preserve compatible ids and hash longer/unsupported AgentCore ids so
    # multi-turn conversations retain a stable Bedrock Agent session.
    session_id = normalize_session_id(
        getattr(context, "session_id", None) or payload.get("sessionId")
    )

    response = await asyncio.to_thread(
        client.invoke_agent,
        agentId=AGENT_ID,
        agentAliasId=AGENT_ALIAS_ID,
        sessionId=session_id,
        inputText=prompt,
    )
    completion = iter(response["completion"])
    while True:
        event = await asyncio.to_thread(next_completion_event, completion)
        if event is END_OF_COMPLETION:
            break
        chunk = event.get("chunk")
        if chunk and "bytes" in chunk:
            yield chunk["bytes"].decode("utf-8")


if __name__ == "__main__":
    app.run()
