"""Gateway capability — auto-generated by agentcore CLI.

Provides MCP gateway client integration for Google ADK agents.
Gateway URLs are auto-discovered from AGENTCORE_GATEWAY_*_URL
environment variables set by CDK at deploy time.

Usage:
    from capabilities.gateway import get_gateway_toolsets

    toolsets = get_gateway_toolsets()
    # pass toolsets to your ADK agent
"""
import os
import logging

from google.adk.tools.mcp_tool.mcp_toolset import MCPToolset
from google.adk.tools.mcp_tool.mcp_session_manager import StreamableHTTPConnectionParams

logger = logging.getLogger(__name__)


def discover_gateways() -> dict[str, dict[str, str]]:
    """Scan environment for gateway configurations.

    Returns dict of gateway_name -> {"url": ..., "auth_type": ..., "credential_provider": ...}
    """
    gateways = {}
    for key, value in os.environ.items():
        if key.startswith("AGENTCORE_GATEWAY_") and key.endswith("_URL"):
            name = key.removeprefix("AGENTCORE_GATEWAY_").removesuffix("_URL")
            gateways[name] = {
                "url": value,
                "auth_type": os.getenv(f"AGENTCORE_GATEWAY_{name}_AUTH_TYPE", "NONE"),
                "credential_provider": os.getenv(f"AGENTCORE_GATEWAY_{name}_CREDENTIAL_PROVIDER", ""),
            }
    return gateways


def _get_bearer_token(credential_provider: str) -> str | None:
    """Get an OAuth bearer token for a CUSTOM_JWT gateway."""
    if not credential_provider:
        return None
    try:
        from bedrock_agentcore.identity import IdentityClient

        client = IdentityClient()
        token_response = client.get_access_token(provider_name=credential_provider, auth_flow="M2M")
        return token_response.get("access_token")
    except Exception:
        logger.exception("Failed to get bearer token for %s", credential_provider)
        return None


def get_gateway_toolsets() -> list[MCPToolset]:
    """Get Google ADK MCPToolset instances for all configured gateways.

    Returns a list of MCPToolset instances that can be passed to your ADK agent.
    """
    gateways = discover_gateways()
    if not gateways:
        logger.info("No gateway URLs found — gateway tools disabled")
        return []

    toolsets = []
    for gw_name, gw_config in gateways.items():
        url = gw_config["url"]
        auth_type = gw_config["auth_type"]

        try:
            if auth_type == "AWS_IAM":
                import httpx
                from mcp_proxy_for_aws.sigv4_helper import SigV4HTTPXAuth, create_aws_session

                session = create_aws_session()
                auth = SigV4HTTPXAuth(session.get_credentials(), "bedrock-agentcore", session.region_name)
                toolsets.append(
                    MCPToolset(
                        connection_params=StreamableHTTPConnectionParams(
                            url=url,
                            httpx_client_factory=lambda auth=auth: httpx.AsyncClient(auth=auth),
                        )
                    )
                )
            elif auth_type == "CUSTOM_JWT":
                token = _get_bearer_token(gw_config["credential_provider"])
                headers = {"Authorization": f"Bearer {token}"} if token else None
                toolsets.append(MCPToolset(connection_params=StreamableHTTPConnectionParams(url=url, headers=headers)))
            else:
                toolsets.append(MCPToolset(connection_params=StreamableHTTPConnectionParams(url=url)))

            logger.info("Created toolset for gateway %s (auth: %s)", gw_name, auth_type)
        except Exception:
            logger.exception("Failed to create toolset for gateway %s", gw_name)

    return toolsets
