"""Gateway capability — auto-generated by agentcore CLI.

Provides MCP gateway client integration using the standard MCP SDK.
Gateway URLs are auto-discovered from AGENTCORE_GATEWAY_*_URL
environment variables set by CDK at deploy time.

This generic module is for BYO (bring-your-own) agents. Adapt the
get_gateway_tools() function to your framework's tool format.

Usage:
    from capabilities.gateway import initialize, get_gateway_tools, shutdown

    # In your async setup:
    await initialize()
    tools = await get_gateway_tools()

    # On shutdown:
    await shutdown()
"""
import os
import logging
from contextlib import AsyncExitStack
from typing import Any

from mcp import ClientSession
from mcp.client.streamable_http import streamablehttp_client

logger = logging.getLogger(__name__)

_exit_stack: AsyncExitStack | None = None
_sessions: list[dict[str, Any]] = []
_initialized = False


def discover_gateways() -> dict[str, dict[str, str]]:
    """Scan environment for gateway configurations.

    Returns dict of gateway_name -> {"url": ..., "auth_type": ..., "credential_provider": ...}
    """
    gateways = {}
    for key, value in os.environ.items():
        if key.startswith("AGENTCORE_GATEWAY_") and key.endswith("_URL"):
            name = key.removeprefix("AGENTCORE_GATEWAY_").removesuffix("_URL")
            gateways[name] = {
                "url": value,
                "auth_type": os.getenv(f"AGENTCORE_GATEWAY_{name}_AUTH_TYPE", "NONE"),
                "credential_provider": os.getenv(f"AGENTCORE_GATEWAY_{name}_CREDENTIAL_PROVIDER", ""),
            }
    return gateways


def _get_bearer_token(credential_provider: str) -> str | None:
    """Get an OAuth bearer token for a CUSTOM_JWT gateway."""
    if not credential_provider:
        return None
    try:
        from bedrock_agentcore.identity import IdentityClient

        client = IdentityClient()
        token_response = client.get_access_token(provider_name=credential_provider, auth_flow="M2M")
        return token_response.get("access_token")
    except Exception:
        logger.exception("Failed to get bearer token for %s", credential_provider)
        return None


async def _connect_gateway(stack: AsyncExitStack, name: str, url: str, auth_type: str, credential_provider: str) -> ClientSession:
    """Create an MCP ClientSession for a single gateway."""
    if auth_type == "AWS_IAM":
        from mcp_proxy_for_aws.client import aws_iam_streamablehttp_client

        read_stream, write_stream, _ = await stack.enter_async_context(
            aws_iam_streamablehttp_client(url, aws_service="bedrock-agentcore", aws_region=os.environ.get("AWS_REGION"))
        )
    elif auth_type == "CUSTOM_JWT":
        token = _get_bearer_token(credential_provider)
        headers = {"Authorization": f"Bearer {token}"} if token else {}
        read_stream, write_stream, _ = await stack.enter_async_context(streamablehttp_client(url, headers=headers))
    else:
        read_stream, write_stream, _ = await stack.enter_async_context(streamablehttp_client(url))

    session = await stack.enter_async_context(ClientSession(read_stream, write_stream))
    await session.initialize()
    return session


async def initialize():
    """Connect to all discovered gateways. Safe to call multiple times."""
    global _exit_stack, _sessions, _initialized

    if _initialized:
        return

    gateways = discover_gateways()
    if not gateways:
        logger.info("No gateway URLs found — gateway tools disabled")
        _initialized = True
        return

    _exit_stack = AsyncExitStack()
    await _exit_stack.__aenter__()

    for gw_name, gw_config in gateways.items():
        try:
            session = await _connect_gateway(
                _exit_stack, gw_name, gw_config["url"], gw_config["auth_type"], gw_config["credential_provider"]
            )
            _sessions.append({"name": gw_name, "session": session})
            logger.info("Connected to gateway %s (auth: %s)", gw_name, gw_config["auth_type"])
        except Exception:
            logger.exception("Failed to connect to gateway %s", gw_name)

    _initialized = True


async def get_gateway_tools() -> list:
    """Get MCP tools from all connected gateways.

    Returns a list of MCP Tool objects. Call initialize() first,
    or this will auto-initialize on first call.
    """
    if not _initialized:
        await initialize()

    tools = []
    for entry in _sessions:
        try:
            result = await entry["session"].list_tools()
            tools.extend(result.tools)
            logger.info("Loaded %d tools from gateway %s", len(result.tools), entry["name"])
        except Exception:
            logger.exception("Failed to list tools from gateway %s", entry["name"])

    return tools


async def shutdown():
    """Clean up gateway connections. Call on process exit."""
    global _exit_stack, _sessions, _initialized
    if _exit_stack:
        await _exit_stack.aclose()
    _exit_stack = None
    _sessions = []
    _initialized = False
