"""Gateway capability — auto-generated by agentcore CLI.

Provides MCP gateway client integration for LangChain/LangGraph agents.
Gateway URLs are auto-discovered from AGENTCORE_GATEWAY_*_URL
environment variables set by CDK at deploy time.

Usage:
    from capabilities.gateway import get_gateway_mcp_client

    async with get_gateway_mcp_client() as mcp_client:
        tools = mcp_client.get_tools()
        # use tools with your LangChain agent
"""
import os
import logging

from langchain_mcp_adapters.client import MultiServerMCPClient

logger = logging.getLogger(__name__)


def discover_gateways() -> dict[str, dict[str, str]]:
    """Scan environment for gateway configurations.

    Returns dict of gateway_name -> {"url": ..., "auth_type": ..., "credential_provider": ...}
    """
    gateways = {}
    for key, value in os.environ.items():
        if key.startswith("AGENTCORE_GATEWAY_") and key.endswith("_URL"):
            name = key.removeprefix("AGENTCORE_GATEWAY_").removesuffix("_URL")
            gateways[name] = {
                "url": value,
                "auth_type": os.getenv(f"AGENTCORE_GATEWAY_{name}_AUTH_TYPE", "NONE"),
                "credential_provider": os.getenv(f"AGENTCORE_GATEWAY_{name}_CREDENTIAL_PROVIDER", ""),
            }
    return gateways


def _get_bearer_token(credential_provider: str) -> str | None:
    """Get an OAuth bearer token for a CUSTOM_JWT gateway."""
    if not credential_provider:
        return None
    try:
        from bedrock_agentcore.identity import IdentityClient

        client = IdentityClient()
        token_response = client.get_access_token(provider_name=credential_provider, auth_flow="M2M")
        return token_response.get("access_token")
    except Exception:
        logger.exception("Failed to get bearer token for %s", credential_provider)
        return None


def get_gateway_mcp_client() -> MultiServerMCPClient | None:
    """Get a MultiServerMCPClient connected to all configured gateways.

    Returns a MultiServerMCPClient that can be used as an async context manager,
    or None if no gateways are configured.

    Usage:
        client = get_gateway_mcp_client()
        if client:
            async with client:
                tools = client.get_tools()
    """
    gateways = discover_gateways()
    if not gateways:
        logger.info("No gateway URLs found — gateway tools disabled")
        return None

    servers = {}
    for gw_name, gw_config in gateways.items():
        url = gw_config["url"]
        auth_type = gw_config["auth_type"]

        try:
            if auth_type == "AWS_IAM":
                from mcp_proxy_for_aws.sigv4_helper import SigV4HTTPXAuth, create_aws_session

                session = create_aws_session()
                auth = SigV4HTTPXAuth(session.get_credentials(), "bedrock-agentcore", session.region_name)
                servers[gw_name] = {"transport": "streamable_http", "url": url, "auth": auth}
            elif auth_type == "CUSTOM_JWT":
                token = _get_bearer_token(gw_config["credential_provider"])
                headers = {"Authorization": f"Bearer {token}"} if token else None
                servers[gw_name] = {"transport": "streamable_http", "url": url, "headers": headers}
            else:
                servers[gw_name] = {"transport": "streamable_http", "url": url}

            logger.info("Configured gateway %s (auth: %s)", gw_name, auth_type)
        except Exception:
            logger.exception("Failed to configure gateway %s", gw_name)

    if not servers:
        return None

    return MultiServerMCPClient(servers)
