"""Gateway capability — auto-generated by agentcore CLI.

Provides MCP gateway client integration for Strands agents.
Gateway URLs are auto-discovered from AGENTCORE_GATEWAY_*_URL
environment variables set by CDK at deploy time.

Usage:
    from capabilities.gateway import get_gateway_tools

    tools = get_gateway_tools()
    agent = Agent(model=load_model(), tools=tools)
"""
import os
import logging

from mcp.client.streamable_http import streamablehttp_client
from strands.tools.mcp.mcp_client import MCPClient

logger = logging.getLogger(__name__)


def discover_gateways() -> dict[str, dict[str, str]]:
    """Scan environment for gateway configurations.

    Returns dict of gateway_name -> {"url": ..., "auth_type": ..., "credential_provider": ...}
    """
    gateways = {}
    for key, value in os.environ.items():
        if key.startswith("AGENTCORE_GATEWAY_") and key.endswith("_URL"):
            name = key.removeprefix("AGENTCORE_GATEWAY_").removesuffix("_URL")
            gateways[name] = {
                "url": value,
                "auth_type": os.getenv(f"AGENTCORE_GATEWAY_{name}_AUTH_TYPE", "NONE"),
                "credential_provider": os.getenv(f"AGENTCORE_GATEWAY_{name}_CREDENTIAL_PROVIDER", ""),
            }
    return gateways


def _get_bearer_token(credential_provider: str) -> str | None:
    """Get an OAuth bearer token for a CUSTOM_JWT gateway."""
    if not credential_provider:
        return None
    try:
        from bedrock_agentcore.identity import IdentityClient

        client = IdentityClient()
        token_response = client.get_access_token(provider_name=credential_provider, auth_flow="M2M")
        return token_response.get("access_token")
    except Exception:
        logger.exception("Failed to get bearer token for %s", credential_provider)
        return None


def _create_mcp_client(name: str, url: str, auth_type: str, credential_provider: str) -> MCPClient | None:
    """Create a Strands MCPClient for a single gateway."""
    try:
        if auth_type == "AWS_IAM":
            from mcp_proxy_for_aws.client import aws_iam_streamablehttp_client

            region = os.environ.get("AWS_REGION", os.environ.get("AWS_DEFAULT_REGION"))
            return MCPClient(
                lambda u=url, r=region: aws_iam_streamablehttp_client(
                    u, aws_service="bedrock-agentcore", aws_region=r
                )
            )
        elif auth_type == "CUSTOM_JWT":
            token = _get_bearer_token(credential_provider)
            headers = {"Authorization": f"Bearer {token}"} if token else {}
            return MCPClient(lambda u=url, h=headers: streamablehttp_client(u, headers=h))
        else:
            return MCPClient(lambda u=url: streamablehttp_client(u))
    except Exception:
        logger.exception("Failed to create MCP client for gateway %s", name)
        return None


def get_gateway_tools() -> list[MCPClient]:
    """Get Strands MCPClient tool providers for all configured gateways.

    Returns a list of MCPClient instances that can be passed directly
    to the Agent tools parameter.
    """
    gateways = discover_gateways()
    if not gateways:
        logger.info("No gateway URLs found — gateway tools disabled")
        return []

    clients = []
    for gw_name, gw_config in gateways.items():
        client = _create_mcp_client(
            gw_name, gw_config["url"], gw_config["auth_type"], gw_config["credential_provider"]
        )
        if client:
            clients.append(client)
            logger.info("Created MCP client for gateway %s (auth: %s)", gw_name, gw_config["auth_type"])

    return clients
